export const BRANDS = [
  { l: '🛒', n: 'Shopify', c: 'bg-emerald-50' },
  { l: '📦', n: 'WooCommerce', c: 'bg-purple-50' },
  { l: '🔥', n: 'Daraz', c: 'bg-orange-100' },
  { l: '🥬', n: 'Chaldal', c: 'bg-green-50' },
  { l: '🏬', n: 'Evaly', c: 'bg-red-50' },
  { l: '🍎', n: 'Pickaboo', c: 'bg-slate-50' },
  { l: '🛍️', n: 'Aarong', c: 'bg-amber-50' },
  { l: '🎨', n: 'Shajgoj', c: 'bg-pink-50' },
  { l: '✨', n: 'Othoba', c: 'bg-blue-50' },
  { l: '🏮', n: 'Alibaba', c: 'bg-orange-50' },
  { l: '👠', n: 'Rokomari', c: 'bg-red-50' },
  { l: '👟', n: 'Bata BD', c: 'bg-red-50' },
  { l: '👗', n: 'PriyoShop', c: 'bg-blue-50' },
  { l: '🚚', n: 'Pathao', c: 'bg-red-50' },
  { l: '💎', n: 'Diamond World', c: 'bg-blue-50' },
  { l: '⚡', n: 'Amana Big', c: 'bg-yellow-50' },
  { l: '📱', n: 'Gadget & Gear', c: 'bg-slate-100' },
  { l: '🥛', n: 'Khaas Food', c: 'bg-green-50' },
];
